### PR TITLE
Exception for WebSocketClosedEvent

### PR DESCRIPTION
**Pull request by csuvajit**

### CODE REVIEW

**Comment by appellation** [comment]
This should probably be handled more gracefully, since many of those events are recoverable simply by reconnecting. I'm not sure if Lavalink does anything on its end to handle that, but if not it's definitely something we can do on the client library side to make the developer experience much nicer.

**Comment by ridays2001** [comment]
I think Lavalink does it because the people using the original Java version don't experience this problem.

**Comment by appellation** [comment]
> 
> 
> I think Lavalink does it because the people using the original Java version don't experience this problem.

Does this mean that Lavalink only forwards unrecoverable close codes? The Lavalink documentation on this subject is a bit sparse, and it's hard for me to test personally since I no longer use it; however, the implication here is that it sends any and all voice websocket close events.

image

**Comment by csuvajit** [comment]
I should have explained! This is not about close code.
If we kick the bot from voice channel, lavalink emits `WebSocketClosedEvent` event which skips the currently playing song. 
A month ago @ridays2001 shared this issue in Lavalibs server.

image

**Comment by ridays2001** [comment]
And the song keeps on playing even when it's supposed to be paused. I didn't notice it before. But, after some debugging, I found that out. Once the bot leaves the VC, even if the song was paused, it automatically resumes the song in the background... @csuvajit told me that this WebSocketClosed caused the problem...

**Comment by ridays2001** [comment]
But, when I asked around in the JDA server, I found out that people using original Java client don't experience this issue... That's why I thought that it's fixed in Lavalink

**Comment by appellation** [comment]
Ah, sure, that makes sense. Thank you for clarifying.

**Pull request merged**
